# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "JSONStream-0.7.4" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-0.7.4.tgz";
        sha1 = "734290e41511eea7c2cfe151fbf9a563a97b9786";
      };
    };
    "csv-parse-0.0.3" = {
      name = "csv-parse";
      packageName = "csv-parse";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/csv-parse/-/csv-parse-0.0.3.tgz";
        sha1 = "c7bd3612c74766d323a544f46af0d3090fc8c531";
      };
    };
    "csv-record-parser-0.0.4" = {
      name = "csv-record-parser";
      packageName = "csv-record-parser";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/csv-record-parser/-/csv-record-parser-0.0.4.tgz";
        sha1 = "b607919ab5a5e416bd4a69171dcaedeb00998e33";
      };
    };
    "csv-record-parser-stream-0.0.3" = {
      name = "csv-record-parser-stream";
      packageName = "csv-record-parser-stream";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/csv-record-parser-stream/-/csv-record-parser-stream-0.0.3.tgz";
        sha1 = "f307dcb280c4faf8e975b7569dab0234d31aaed3";
      };
    };
    "csv-stringify-2.0.4" = {
      name = "csv-stringify";
      packageName = "csv-stringify";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/csv-stringify/-/csv-stringify-2.0.4.tgz";
        sha512 = "20kxjdx43s1p90qcwz3892ck2q4di3p4h875h936782z7pabymwnb13h46q7nygkcbjj1cmrb3s73r9hamdhh2c521md0hpsv20jvxf";
      };
    };
    "debug-0.8.1" = {
      name = "debug";
      packageName = "debug";
      version = "0.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-0.8.1.tgz";
        sha1 = "20ff4d26f5e422cb68a1bacbbb61039ad8c1c130";
      };
    };
    "dot-lens-1.2.3" = {
      name = "dot-lens";
      packageName = "dot-lens";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-lens/-/dot-lens-1.2.3.tgz";
        sha1 = "473572c355885202711ab2af86fa9d21c89b45a7";
      };
    };
    "epipebomb-0.1.1" = {
      name = "epipebomb";
      packageName = "epipebomb";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/epipebomb/-/epipebomb-0.1.1.tgz";
        sha1 = "aca7cc380881854142abe64b6723c792676e00b2";
      };
    };
    "join-stream-0.0.0" = {
      name = "join-stream";
      packageName = "join-stream";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/join-stream/-/join-stream-0.0.0.tgz";
        sha1 = "b6e5763a9adafe7827ab573ff548456c796977ed";
      };
    };
    "jsonparse-0.0.5" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-0.0.5.tgz";
        sha1 = "330542ad3f0a654665b778f3eb2d9a9fa507ac64";
      };
    };
    "lodash.get-4.4.2" = {
      name = "lodash.get";
      packageName = "lodash.get";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.get/-/lodash.get-4.4.2.tgz";
        sha1 = "2d177f652fa31e939b4438d5341499dfa3825e99";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "tableize-array-1.1.0" = {
      name = "tableize-array";
      packageName = "tableize-array";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tableize-array/-/tableize-array-1.1.0.tgz";
        sha1 = "9a61476610e1131d55054c1766690b7415912faf";
      };
    };
    "tableize-csv-parser-0.0.1" = {
      name = "tableize-csv-parser";
      packageName = "tableize-csv-parser";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tableize-csv-parser/-/tableize-csv-parser-0.0.1.tgz";
        sha1 = "fdbe13dee2c335e2ea8533c1422955c0182c2924";
      };
    };
    "through-0.1.4" = {
      name = "through";
      packageName = "through";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-0.1.4.tgz";
        sha1 = "8059576d833089b3c18eccd37580bf9cc5b59130";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
  };
  args = {
    name = "jb55-json2csv";
    packageName = "jb55-json2csv";
    version = "3.0.0";
    src = ./.;
    dependencies = [
      sources."JSONStream-0.7.4"
      sources."csv-parse-0.0.3"
      sources."csv-record-parser-0.0.4"
      sources."csv-record-parser-stream-0.0.3"
      sources."csv-stringify-2.0.4"
      sources."debug-0.8.1"
      sources."dot-lens-1.2.3"
      sources."epipebomb-0.1.1"
      (sources."join-stream-0.0.0" // {
        dependencies = [
          sources."through-0.1.4"
        ];
      })
      sources."jsonparse-0.0.5"
      sources."lodash.get-4.4.2"
      sources."minimist-0.0.8"
      sources."tableize-array-1.1.0"
      sources."tableize-csv-parser-0.0.1"
      sources."through-2.3.8"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "like zeMirco/json2csv but supports nested fields and arrays";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}